import { PartialType } from '@nestjs/mapped-types';
import { CreateAutoGeneratedContentDto } from './create-auto-generated-content.dto';

export class UpdateAutoGeneratedContentDto extends PartialType(CreateAutoGeneratedContentDto) {}
