import { Controller, Get, Post, Body, Patch, Param, Delete } from '@nestjs/common';
import { AutoGeneratedContentService } from './auto-generated-content.service';
import { CreateAutoGeneratedContentDto } from './dto/create-auto-generated-content.dto';
import { UpdateAutoGeneratedContentDto } from './dto/update-auto-generated-content.dto';

@Controller('auto-generated-content')
export class AutoGeneratedContentController {
  constructor(private readonly autoGeneratedContentService: AutoGeneratedContentService) {}

  @Post()
  createTable(@Body() createAutoGeneratedContentDto: CreateAutoGeneratedContentDto) {
    return this.autoGeneratedContentService.createTable(createAutoGeneratedContentDto);
  }

  @Get()
  findAll() {
    return this.autoGeneratedContentService.findAll();
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.autoGeneratedContentService.findOne(+id);
  }

  @Patch(':id')
  update(@Param('id') id: string, @Body() updateAutoGeneratedContentDto: UpdateAutoGeneratedContentDto) {
    return this.autoGeneratedContentService.update(+id, updateAutoGeneratedContentDto);
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.autoGeneratedContentService.remove(+id);
  }
}
