import { Controller, Get, Body, Patch, Param, Delete, Post } from '@nestjs/common';
import { AutoGeneratedContentService } from './auto-generated-content.service';
import { CreateAutoGeneratedContentDto } from './dto/create-auto-generated-content.dto';
import { UpdateAutoGeneratedContentDto } from './dto/update-auto-generated-content.dto';

@Controller('auto-generated-content')
export class AutoGeneratedContentController {
  constructor(private readonly autoGeneratedContentService: AutoGeneratedContentService) {}

  @Post(':tableName')
  saveTableContent(
    @Param('tableName') tableName: string, 
    @Body() payload: any) {
    return this.autoGeneratedContentService.saveTableContent(tableName, payload);
  }

  @Get('table/:tableName')
  findTableContentByTableName(@Param('tableName') tableName: string) {
    return this.autoGeneratedContentService.findTableContentByTableName(tableName);
  }

  @Patch(':tableName/:id')
  updateTableRow(
    @Param('tableName') tableName: string,
    @Param('id') id: string,  
    @Body() updateAutoGeneratedContentDto: UpdateAutoGeneratedContentDto) {
    return this.autoGeneratedContentService.updateTableRow(tableName, id, updateAutoGeneratedContentDto);
  }

  @Delete(':tableName/:id')
  deleteTableRow(
    @Param('tableName') tableName: string,
    @Param('id') id: string ) {
    return this.autoGeneratedContentService.deleteTableRow(tableName, id);
  }

}
