import { Module } from '@nestjs/common';
import { AutoGeneratedContentService } from './auto-generated-content.service';
import { AutoGeneratedContentController } from './auto-generated-content.controller';

@Module({
  controllers: [AutoGeneratedContentController],
  providers: [AutoGeneratedContentService],
})
export class AutoGeneratedContentModule {}
