import { Module } from '@nestjs/common';
import { AutoGeneratedContentService } from './auto-generated-content.service';
import { AutoGeneratedContentController } from './auto-generated-content.controller';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TableViz } from '../table-viz/entities/table-viz.entity';
import { CustomFormInput } from '../custom-form-input/entities/custom-form-input.entity';

@Module({
  imports:[TypeOrmModule.forFeature([TableViz, CustomFormInput])],
  controllers: [AutoGeneratedContentController],
  providers: [AutoGeneratedContentService],
})
export class AutoGeneratedContentModule {}
