import { Injectable } from '@nestjs/common';
import { CreateAutoGeneratedContentDto } from './dto/create-auto-generated-content.dto';
import { UpdateAutoGeneratedContentDto } from './dto/update-auto-generated-content.dto';
import { CustomFormInput } from '../custom-form-input/entities/custom-form-input.entity';
import { ColumnType, DataSource, EntitySchema, EntitySchemaColumnOptions } from 'typeorm';
import { CreateCustomFormInputDto } from '../custom-form-input/dto/create-custom-form-input.dto';

@Injectable()
export class AutoGeneratedContentService {

  constructor(private _dataSource: DataSource) { }

  createTable(createAutoGeneratedContentDto: CreateAutoGeneratedContentDto) {

  }

  findAll() {
    return `This action returns all autoGeneratedContent`;
  }

  findOne(id: number) {
    return `This action returns a #${id} autoGeneratedContent`;
  }

  update(id: number, updateAutoGeneratedContentDto: UpdateAutoGeneratedContentDto) {
    return `This action updates a #${id} autoGeneratedContent`;
  }

  remove(id: number) {
    return `This action removes a #${id} autoGeneratedContent`;
  }

  createDynamicEntity(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    const entitySchemaColumns = {} as Record<string, EntitySchemaColumnOptions>;
    entitySchemaColumns["id"] = {
      type: 'uuid',
      primary: true,
      generated: true,
      unique: true,
      nullable: false,
    };

    for (let customInput of customFormInputs) {
      entitySchemaColumns[customInput.columnName] = { type: customInput.columnType }
    }

    return new EntitySchema({
      name: `Entity_${tableName}`,
      tableName: `auto_${tableName}`,
      columns: entitySchemaColumns
    });
  }

  async createDatabaseTable(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    const dynamicEntity = this.createDynamicEntity(tableName, customFormInputs);

    this._dataSource.setOptions({
      entities: [...[], dynamicEntity]
    })

    await this._dataSource.synchronize(false); // Only adds new table
    return { message: `Tenant ${tableName} table created.` };
  }
}
