import { Test, TestingModule } from '@nestjs/testing';
import { AutoGeneratedContentService } from './auto-generated-content.service';

describe('AutoGeneratedContentService', () => {
  let service: AutoGeneratedContentService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [AutoGeneratedContentService],
    }).compile();

    service = module.get<AutoGeneratedContentService>(AutoGeneratedContentService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });
});
