import { Injectable, OnModuleInit } from '@nestjs/common';
import { CreateAutoGeneratedContentDto } from './dto/create-auto-generated-content.dto';
import { UpdateAutoGeneratedContentDto } from './dto/update-auto-generated-content.dto';
import { CustomFormInput } from '../custom-form-input/entities/custom-form-input.entity';
import { Column, DataSource, Entity, EntitySchema, EntitySchemaColumnOptions, PrimaryGeneratedColumn, Repository, Table, TableColumnOptions } from 'typeorm';
import { CreateCustomFormInputDto } from '../custom-form-input/dto/create-custom-form-input.dto';
import { TableViz } from '../table-viz/entities/table-viz.entity';
import { InjectRepository } from '@nestjs/typeorm';

@Injectable()
export class AutoGeneratedContentService {

  constructor(private _dataSource: DataSource,
              @InjectRepository(TableViz)
              private _tableVizRepository: Repository<TableViz>) { }


  findAll() {
    return `This action returns all autoGeneratedContent`;
  }

  findOne(id: number) {
    return `This action returns a #${id} autoGeneratedContent`;
  }

  async saveTableContent(tableName: string, payload: any) {
    this._dataSource.createQueryBuilder()
      .insert()
      .into(`my_app.${tableName}`)
      .values(payload)
      .execute();
  }

  async findTableContentByTableName(tableName: string) {
    return await this._dataSource.createQueryBuilder()
      .select('*')
      .from(`my_app.${tableName}`, 't')
      .execute()
  }

  update(id: number, updateAutoGeneratedContentDto: UpdateAutoGeneratedContentDto) {
    return `This action updates a #${id} autoGeneratedContent`;
  }

  remove(id: number) {
    return `This action removes a #${id} autoGeneratedContent`;
  }

  /**
   * Create entity schema based on specific table name and column configs
   * @param tableName The name of the table associated to the entity we wish to create
   * @param customFormInputs An array of input config used for columns creation
   * @returns The entity schema created
   */
  /*createDynamicEntity(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    const entitySchemaColumns = {} as Record<string, EntitySchemaColumnOptions>;
    entitySchemaColumns["id"] = {
      type: 'uuid',
      primary: true,
      generated: true,
      unique: true,
      nullable: false,
    };

    for (let customInput of customFormInputs) {
      entitySchemaColumns[customInput.columnName] = { type: customInput.columnType }
    }

    return new EntitySchema({
      name: `Entity_${tableName}`,
      tableName: tableName,
      columns: entitySchemaColumns
    });
  }*/


  /**
   * Create a postgres table in my_app schema
   * @param tableName The name of the table to be created 
   * @param customFormInputs An array of input config used for columns creation
   * @returns success message
   */
  async createDatabaseTable(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    const columns: Array<TableColumnOptions> = [];

    columns.push({
      name: 'id',
      type: 'uuid',
      isPrimary: true,
      isGenerated: true,
      generationStrategy: 'uuid',
      isUnique: true,
      isNullable: false
    });

    for (let customInput of customFormInputs) {
      columns.push({ name: customInput.columnName, type: customInput.columnType });
    }

    const queryRunner = this._dataSource.createQueryRunner();
    await queryRunner.createTable(
      new Table({
        name: tableName,
        columns: columns
      }),
      true
    );
    await queryRunner.release();

    return { message: `Tenant ${tableName} table created.` };
  }

}
