import { Test, TestingModule } from '@nestjs/testing';
import { AutoGeneratedContentController } from './auto-generated-content.controller';
import { AutoGeneratedContentService } from './auto-generated-content.service';

describe('AutoGeneratedContentController', () => {
  let controller: AutoGeneratedContentController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AutoGeneratedContentController],
      providers: [AutoGeneratedContentService],
    }).compile();

    controller = module.get<AutoGeneratedContentController>(AutoGeneratedContentController);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });
});
