import { Injectable } from '@nestjs/common';
import { CreateAutoGeneratedContentDto } from './dto/create-auto-generated-content.dto';
import { UpdateAutoGeneratedContentDto } from './dto/update-auto-generated-content.dto';
import { CustomFormInput } from '../custom-form-input/entities/custom-form-input.entity';
import { ColumnType, DataSource, EntitySchema, EntitySchemaColumnOptions, Table, TableColumnOptions } from 'typeorm';
import { CreateCustomFormInputDto } from '../custom-form-input/dto/create-custom-form-input.dto';

@Injectable()
export class AutoGeneratedContentService {

  constructor(private _dataSource: DataSource) { }

  findAll() {
    return `This action returns all autoGeneratedContent`;
  }

  findOne(id: number) {
    return `This action returns a #${id} autoGeneratedContent`;
  }

  update(id: number, updateAutoGeneratedContentDto: UpdateAutoGeneratedContentDto) {
    return `This action updates a #${id} autoGeneratedContent`;
  }

  remove(id: number) {
    return `This action removes a #${id} autoGeneratedContent`;
  }

  createDynamicEntity(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    const entitySchemaColumns = {} as Record<string, EntitySchemaColumnOptions>;
    entitySchemaColumns["id"] = {
      type: 'uuid',
      primary: true,
      generated: true,
      unique: true,
      nullable: false,
    };

    for (let customInput of customFormInputs) {
      entitySchemaColumns[customInput.columnName] = { type: customInput.columnType }
    }

    return new EntitySchema({
      name: `Entity_${tableName}`,
      tableName: `auto_${tableName}`,
      columns: entitySchemaColumns
    });
  }

  async createDatabaseTable(tableName: string, customFormInputs: CreateCustomFormInputDto[]) {
    /*const dynamicEntity = this.createDynamicEntity(tableName, customFormInputs);
    
    console.log(dynamicEntity);
    console.log(this._dataSource.options.entities);
    
    this._dataSource.setOptions({
      entities: [...(this._dataSource.options.entities as Array<EntitySchema>), dynamicEntity],
    });*/

    const columns: Array<TableColumnOptions> = [];
    columns.push({
      name: 'id',
      type: 'uuid',
      isPrimary: true,
      isGenerated: true,
      generationStrategy: 'uuid',
      isUnique: true,
      isNullable: false
    });

    for (let customInput of customFormInputs) {
      columns.push({ name: customInput.columnName, type: customInput.columnType });
    }

    const queryRunner = this._dataSource.createQueryRunner();

    await queryRunner.createTable(
      new Table({
        name: tableName,
        columns: columns
      }),
      true
    );

    await queryRunner.release();

    //await this._dataSource.synchronize(false); // Only adds new table

    return { message: `Tenant ${tableName} table created.` };
  }
}
