import { Injectable } from '@nestjs/common';
import { CreateCustomFormInputDto } from './dto/create-custom-form-input.dto';
import { UpdateCustomFormInputDto } from './dto/update-custom-form-input.dto';
import { InjectRepository } from '@nestjs/typeorm';
import { CustomFormInput } from './entities/custom-form-input.entity';
import { ColumnType, Repository } from 'typeorm';
import { stringToLowerCaseWithUnderscore } from 'src/core/utils/string-transfo-util';
import { SimpleColumnType, SpatialColumnType, WithLengthColumnType, WithPrecisionColumnType, WithWidthColumnType } from 'typeorm/driver/types/ColumnTypes';
import { AutoGeneratedContentService } from '../auto-generated-content/auto-generated-content.service';

@Injectable()
export class CustomFormInputService {

  inputTypeDatabaseTypeMap = new Map<string, WithPrecisionColumnType | WithLengthColumnType | WithWidthColumnType | SpatialColumnType | SimpleColumnType>([
    ["email", "varchar"],
    ["url", "varchar"],
    ["text", "varchar"],
    ["password", "varchar"],
    ["textarea", "varchar"],
    ["number", "int"],
    ["date", "timestamp"],
    ["date-and-time", "timestamp"],
    ["file", "varchar"],
    ["checkbox", "boolean"]
  ]);

  constructor(@InjectRepository(CustomFormInput)
              private _customFormInputRepository: Repository<CustomFormInput>,
              private _autoGeneratedContentService: AutoGeneratedContentService) {}

  async create(createCustomFormDto: CreateCustomFormInputDto[], tableName: string) {
    createCustomFormDto.forEach(column => {
      column.columnType = this.inputTypeDatabaseTypeMap.get(column.inputType)!;
      column.columnName = stringToLowerCaseWithUnderscore(column.inputLabel);
    });

    console.log("QWERTY");
    const result = await this._autoGeneratedContentService.createDatabaseTable(tableName, createCustomFormDto);
    console.log(result);
    return this._customFormInputRepository.save(createCustomFormDto);
  }

  findAll() {
    return `This action returns all customForm`;
  }

  findOne(id: number) {
    return `This action returns a #${id} customForm`;
  }

  update(id: string, updateCustomFormDto: UpdateCustomFormInputDto) {
    return this._customFormInputRepository.update(id, updateCustomFormDto);
  }

  remove(id: number) {
    return `This action removes a #${id} customForm`;
  }

}
